config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers
  mathjax 'mathjax'
  resources :submissions do
  	resources :annotations
  end
  get 'home/index'
  root 'home#index'
end

app/models/annotation.rb
# == Schema Information
#
# Table name: annotations
#
#  id            :integer          not null, primary key
#  mark          :integer
#  sketch        :json
#  submission_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  comment       :text
#

class Annotation < ActiveRecord::Base
end

app/models/submission.rb
# == Schema Information
#
# Table name: submissions
#
#  id         :integer          not null, primary key
#  roll       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  pages      :json
#

class Submission < ActiveRecord::Base
	mount_uploaders :pages, PageUploader
	has_many :annotations
	accepts_nested_attributes_for :annotations, allow_destroy: true
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController
  before_action :set_annotation, only: [:show, :edit, :update, :destroy]
  before_action :load_submission
  # GET /annotations
  def index
    @annotations = @submission.annotations.all
  end

  # GET /annotations/1
  def show
  end

  # GET /annotations/new
  def new
    @annotation = @submission.annotations.build
  end

  # GET /annotations/1/edit
  def edit
    @annotation = @submission.annotations.find(params[:id])
  end

  # POST /annotations
  def create
    @annotation = @submission.annotations.new(annotation_params)

    if @annotation.save
      redirect_to submission_annotation_path(@submission, @annotation), notice: 'Annotation was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /annotations/1
  def update
    if @annotation.update(annotation_params)
      redirect_to submission_annotation_path(@submission, @annotation), notice: 'Annotation was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /annotations/1
  def destroy
    @annotation.destroy
    redirect_to submission_annotations_url(@submission), notice: 'Annotation was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annotation
      @annotation = Annotation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def annotation_params
      params.require(:annotation).permit(:mark, :sketch, :submission_id, :comment)
    end

    def load_submission
      @submission = Submission.find(params[:submission_id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  # GET /submissions
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1
  def show
    @annotation = Annotation.new
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  def create
    @submission = Submission.new(submission_params)

    if @submission.save
      redirect_to @submission, notice: 'Submission was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /submissions/1
  def update
    if @submission.update(submission_params)
      redirect_to @submission, notice: 'Submission was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /submissions/1
  def destroy
    @submission.destroy
    redirect_to submissions_url, notice: 'Submission was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def submission_params
      params.require(:submission).permit(:roll, {pages: []})
    end
end

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/annotations/_form.html.erb
<%= simple_form_for([@submission, @annotation]) do |f| %>
  <div class="form-inputs">
    <%= f.input :mark %>
    <%= f.input :sketch, as: :string, input_html: {id: "json"} %>
    <%= f.input :comment %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/annotations/edit.html.erb
<h1>Editing Annotation</h1>
<script type="text/javascript">
  $(document).ready(function(){
    var sketch = __canvas = new Sketch("canvas");
    var jsonTA = document.getElementById("json");
    var dataTA = document.getElementById("data");
    var tmp = <%= @annotation.sketch.to_json.gsub(/\"/, "") %>;
    sketch.loadJSON(tmp);
    $("#clearBtn").click(function(){
       sketch.clear();
       jsonTA.value="";
    });
    $("#showJsonBtn").click(function(){
       jsonTA.value = sketch.getJSON();
    });
    $("#applyJsonBtn").click(function(){
      sketch.loadJSON(jsonTA.value);
    });
  });
</script>
<div class="row">
	<div class="col-md-8">
    <input type="button" value="Clear Screen" id="clearBtn" class="btn btn-danger btn-xs"  > | 
    <input type="button" value="Show JSON" id="showJsonBtn" class="btn btn-success btn-xs" >
  	<canvas id="canvas" width="800" height="1123" style="background: url(<%= @submission.pages[0].url %>) no-repeat"></canvas>
	</div>
	<div class="col-md-4">
    <h2 style="text-align: center;"><%= @submission.roll %></h2>
		<%= render 'form' %>
	</div>	
</div>
<%= link_to 'Show', submission_annotation_path(@submission, @annotation), class: "btn btn-default btn-xs" %> |
<%= link_to 'Back', submission_annotations_path(@submission), class: "btn btn-success btn-xs" %>

app/views/annotations/index.html.erb
<h1>Listing Annotations</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Mark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @annotations.each do |annotation| %>
      <tr>
        <td><%= annotation.mark %></td>
        <td><%= link_to 'Show', submission_annotation_path(@submission, annotation) %></td>
        <td><%= link_to 'Edit', edit_submission_annotation_path(@submission, annotation) %></td>
        <td><%= link_to 'Destroy',  submission_annotation_path(@submission, annotation), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Annotation', new_submission_annotation_path(@submission), class: "btn btn-default btn-xs" %>

app/views/annotations/new.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    var sketch = __canvas = new Sketch("canvas");
    var jsonTA = document.getElementById("json");
    var dataTA = document.getElementById("data");
    $("#clearBtn").click(function(){
       sketch.clear();
    });
    $("#showJsonBtn").click(function(){
       jsonTA.value = sketch.getJSON();
    });
    $("#applyJsonBtn").click(function(){
      sketch.loadJSON(jsonTA.value);
    });
  });
</script>
<div class="row">
	<div class="col-md-8">
    <input type="button" value="Clear Screen" id="clearBtn" class="btn btn-danger btn-xs"  > | 
    <input type="button" value="Show JSON" id="showJsonBtn" class="btn btn-success btn-xs" >
  	<canvas id="canvas" width="800" height="1123" style="background: url(<%= @submission.pages[0].url %>) no-repeat"></canvas>
	</div>
	<div class="col-md-4">
    <h2 style="text-align: center;"><%= @submission.roll %></h2>
		<%= render 'form' %>
	</div>	
</div>
<%= link_to 'Back', submission_annotations_path(@submission), class: "btn btn-success btn-xs" %>

app/views/annotations/show.html.erb
<script type="text/javascript">
  $(document).ready(function(){
	var sketch = new Sketch("canvas");
	var a = <%= @annotation.sketch.to_json.gsub(/\"/, "") %>;
	sketch.loadJSON(a);
  });
</script>
<div class="row">
	<div class="col-md-8">
		<canvas id="canvas" width="800" height="1123" style="background: url(<%= @submission.pages[0].url %>) no-repeat"></canvas>
	</div>

	<div class="col-md-4">
		<p>
			<h1 style="text-align: center;"><%= @submission.roll %> </h1>	
		</p>
		<p>
  			<strong>Mark:</strong>
  			<%= @annotation.mark %>
		</p>
		<p>	
			<strong>Remark</strong>
			<%= @annotation.comment %> 
		</p>
	</div>
</div>


<%= link_to 'Edit', edit_submission_annotation_path(@submission, @annotation), class: "btn btn-info btn-xs" %> |
<%= link_to 'Back', submission_annotations_path(@submission), class: "btn btn-success btn-xs" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
     tex2jax: {
       inlineMath: [ ['$','$'] ],
       processEscapes: true
     }
    });
</script>
  <%= mathjax_tag %>
  <%= csrf_meta_tags %>
  <title>Canvas</title>
</head>
<body>
<%= nav_bar brand: 'Canvas' do %>
	<%= menu_group do %>
		<%= drop_down 'Submissions' do %>
			<%= menu_item 'List All', submissions_path %>
			<%= menu_item 'New', new_submission_path %>
		<% end %> 
	<% end %>
<% end %>
<div class="container-fluid">
	<%= yield %>
</div>
</body>
</html>

app/views/submissions/_form.html.erb
<%= simple_form_for(@submission) do |f| %>
  <div class="form-inputs">
    <%= f.input :roll %>
    <%= f.file_field :pages, multiple: :true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<h1>Listing Submissions</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Roll</th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.roll %></td>
        <% for i in 0..submission.pages.length-1 %>
          <td><%= link_to image_tag(submission.pages[i].thumb.url), "#" %></td>
        <% end %>
        <td><%= link_to 'Grade', submission_annotations_path(submission), class: 'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission), class: 'btn btn-default' %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/submissions/new.html.erb
<div class="col-md-4">
	<h1>New Submission</h1>

	<%= render 'form' %>

	<%= link_to 'Back', submissions_path, class: "btn btn-success btn-xs" %>
</div>

app/views/submissions/show.html.erb
<div class="row">
	<div class="col-md-8">
		<%= link_to 'Edit', edit_submission_path(@submission), class: "btn btn-default btn-xs" %>
		<%= link_to 'Back', submissions_path, class: "btn btn-success btn-xs" %>
		<canvas id="c" width="800" height="1123" style="background: url(<%= @submission.pages[0].url %>) no-repeat"></canvas>
	</div>
	<div class="col-md-4">
		
	</div>	
</div>